# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'ActorCapture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActorCapture
  pod 'SDWebImage'
  pod 'Alamofire'

end
